openapi: 3.0.3
info:
  title: todolist API
  version: 1.0.0
  description: Your project description
paths:
  /completedtask/{site_id}/:
    get:
      operationId: completedtask_retrieve
      parameters:
      - in: path
        name: site_id
        schema:
          type: integer
        required: true
      tags:
      - completedtask
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: completedtask_create
      parameters:
      - in: path
        name: site_id
        schema:
          type: integer
        required: true
      tags:
      - completedtask
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /import/:
    post:
      operationId: import_create
      tags:
      - import
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /incompletedtask/{site_id}/:
    get:
      operationId: incompletedtask_retrieve
      parameters:
      - in: path
        name: site_id
        schema:
          type: integer
        required: true
      tags:
      - incompletedtask
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: incompletedtask_create
      parameters:
      - in: path
        name: site_id
        schema:
          type: integer
        required: true
      tags:
      - incompletedtask
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /post-people/{site_id}/:
    post:
      operationId: post_people_create
      parameters:
      - in: path
        name: site_id
        schema:
          type: integer
        required: true
      tags:
      - post-people
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /post-plant/{site_id}/:
    post:
      operationId: post_plant_create
      parameters:
      - in: path
        name: site_id
        schema:
          type: integer
        required: true
      tags:
      - post-plant
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /sites/{site_id}/machines/:
    get:
      operationId: sites_machines_retrieve
      parameters:
      - in: path
        name: site_id
        schema:
          type: integer
        required: true
      tags:
      - sites
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /sites/{site_id}/people/:
    get:
      operationId: sites_people_retrieve
      parameters:
      - in: path
        name: site_id
        schema:
          type: integer
        required: true
      tags:
      - sites
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /sites/{site_id}/shift-data/:
    get:
      operationId: sites_shift_data_retrieve
      parameters:
      - in: path
        name: site_id
        schema:
          type: integer
        required: true
      tags:
      - sites
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /states/:
    get:
      operationId: states_retrieve
      tags:
      - states
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /states/{state_id}/sites/:
    get:
      operationId: states_sites_retrieve
      parameters:
      - in: path
        name: state_id
        schema:
          type: integer
        required: true
      tags:
      - states
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
