# Generated by Django 5.1.4 on 2025-03-08 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('shift', models.IntegerField(choices=[(1, 'Shift 1'), (2, 'Shift 2')])),
                ('date', models.DateField()),
                ('machines', models.TextField()),
                ('people', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.site')),
            ],
            options={
                'ordering': ['-date', 'shift'],
            },
        ),
        migrations.AddField(
            model_name='site',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.state'),
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('incomplete', 'Incomplete')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='todolist.shiftdata')),
            ],
        ),
        migrations.CreateModel(
            name='IncompleteTaskEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='task_evidence/')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todolist.taskstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Headcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(default=1)),
                ('date', models.DateField()),
                ('shift', models.IntegerField(choices=[(1, 'Shift 1'), (2, 'Shift 2')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.site')),
            ],
            options={
                'unique_together': {('site', 'person_name', 'date', 'shift')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('name', 'state')},
        ),
    ]
