# Generated by Django 5.1.4 on 2025-03-18 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconcilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.CharField(max_length=255)),
                ('lot_no_date', models.CharField(max_length=255)),
                ('used', models.IntegerField()),
                ('used_date', models.CharField(max_length=255)),
                ('left', models.IntegerField()),
                ('left_date', models.CharField(max_length=255)),
                ('returned', models.IntegerField()),
                ('returned_date', models.CharField(max_length=255)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.shift')),
            ],
        ),
    ]
