# Generated by Django 5.1.4 on 2025-03-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
