# Generated by Django 5.1.4 on 2025-03-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskreport',
            name='machinery_used',
        ),
        migrations.AddField(
            model_name='taskreport',
            name='machinery_used',
            field=models.JSONField(default=list),
        ),
    ]
