# Generated by Django 5.1.4 on 2025-01-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcompletereport',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskincompletereport',
            name='task',
        ),
        migrations.AddField(
            model_name='taskcompletereport',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='taskincompletereport',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
