# Generated by Django 5.1.4 on 2025-01-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_remove_taskcompletereport_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcompletereport',
            name='description',
            field=models.TextField(),
        ),
    ]
