# Generated by Django 5.1.4 on 2025-01-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_taskcompletereport_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskincompletereport',
            name='photo',
        ),
        migrations.AlterField(
            model_name='taskincompletereport',
            name='reason',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
