# Generated by Django 5.1.4 on 2025-03-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_reconcilation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_sites',
            field=models.ManyToManyField(blank=True, to='todolist.site'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete'), ('Partially Complete', 'Partially Complete')], default='Incomplete', max_length=20),
        ),
    ]
