# Generated by Django 5.1.4 on 2025-01-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_taskcompletereport_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskincompletereport',
            name='photo',
            field=models.URLField(max_length=1000),
        ),
    ]
