# Generated by Django 5.1.4 on 2025-01-24 16:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_remove_taskincompletereport_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskincompletereport',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskincompletereport',
            name='reason',
            field=models.TextField(),
        ),
    ]
